
#line 3 "lshScanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 152
#define YY_END_OF_BUFFER 153
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[598] =
    {   0,
        0,    0,    2,    2,   16,   16,   20,   20,   24,   24,
        0,    0,    0,    0,    0,    0,    0,    0,  153,  151,
        8,    9,    9,  150,   15,  151,  150,  150,  150,   19,
      150,  150,  150,  150,  150,   13,  150,  149,  150,  150,
      150,  148,  148,  148,  148,  148,   31,  150,   23,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  150,  150,  150,    2,
        4,    3,   16,   17,   16,   20,   21,   20,   24,  152,
       24,   25,   26,   18,   22,    8,    0,    0,    6,   94,
       83,   91,   87,   14,   89,   45,   88,   90,   37,   95,

        1,    0,   92,    0,   13,   42,   47,   46,  149,   69,
       68,   80,   67,  148,  148,  148,  148,  148,  148,   84,
       93,  148,  148,   52,  148,  148,  148,  148,  148,  148,
      148,   49,  148,  148,  148,  148,  148,    0,    0,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,   45,   53,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,   84,   32,   30,    0,    2,    3,    3,    5,   16,
       16,   16,   20,   20,   20,   24,   24,   24,   82,    0,

        0,    7,   13,   81,   83,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  127,  126,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,   51,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      118,  148,  148,  148,  148,  148,  148,  148,   35,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,   64,  148,
      148,  148,  148,   61,   14,  135,  136,  134,   10,  148,
      120,  148,   55,  148,  148,  148,  148,  122,  148,  148,

       65,   47,   46,  148,  138,  137,   59,  148,  148,  130,
      148,  127,  125,  148,  148,  139,  126,  148,  148,  148,
      148,  148,  148,  148,  148,  148,   60,  148,  148,  148,
      148,  148,  148,  148,  144,  147,  148,  148,  148,  148,
      148,  148,  148,  148,   85,  148,  148,   86,  148,  148,
      148,  148,   39,  148,  123,   11,  148,  140,  148,   48,
      148,   57,   63,   34,  148,  148,  148,  148,  148,   73,
      148,  148,   12,  148,  148,  119,  128,  133,  132,  148,
      148,  148,  148,  148,  148,  148,  148,   66,  148,  148,
      148,   76,  148,  148,  148,  148,  148,  148,  148,  148,

      148,  148,  148,  124,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,   62,  148,  148,
       50,  148,  148,  148,  148,  148,  148,  148,  148,  131,
      148,  129,  148,   28,  141,  148,   27,  148,  148,  148,
       75,   74,  148,  148,   40,  148,  148,  105,   33,  148,
       71,  148,   41,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  121,   54,   70,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,   72,   56,  148,   38,
      130,  148,  148,  142,   44,  148,   78,  148,  148,   36,
      143,  148,  103,  148,  148,  148,  148,  148,   98,  148,

      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,   58,  148,   29,   43,  148,
       79,   77,  145,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  116,  148,  148,
      148,  148,  148,  148,   67,  148,  148,  102,  106,  148,
      148,  101,  148,  148,  148,  148,  148,  148,  110,  117,
      148,  148,  148,  148,  148,  148,  148,  148,  104,  108,
      148,  148,  111,  148,  148,  148,  148,  115,  148,  148,
       96,   97,   99,  113,  148,  148,  112,  107,  109,  148,
      146,  148,  114,  148,  148,  100,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,    8,
        8,   12,   13,    8,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    8,    8,   23,   24,   25,   26,   27,   28,
       24,   24,   29,   24,   24,   30,   24,   31,   32,   33,
       24,   34,   35,   36,   37,   24,   24,   24,   24,   24,
        8,   38,    8,   39,   40,   41,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,    8,   68,    8,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       70,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    1,    1,    1,
        1,    1,    1,   71,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    5,    1,    1,    1,    1,    6,    1,    1,    1,
        1,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    6,
        7,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[611] =
    {   0,
        0,    0,   69,   70,   68,   69,   65,   66,   75,   76,
      681,  680,    0,    0,  714,  713,  707,  706,  716,  723,
      713,  723,  723,  693,  723,  710,  723,  691,  701,  723,
      689,   67,   69,  688,   80,   70,   75,  689,   79,  686,
      684,  674,    0,   73,  667,  669,    0,  681,  723,   50,
       62,   69,   77,   76,  122,   78,   80,  651,  644,   66,
      640,   84,  652,  101,   87,  106,  629,  116,  626,    0,
      723,  151,  657,  723,  139,  656,  723,  149,  655,  723,
      130,  723,  723,  723,  723,  690,  670,  687,  723,  723,
      723,  723,  723,  159,  723,  723,  723,  723,  723,  723,

      723,  686,  723,  671,  173,  723,  723,  723,  668,  723,
      723,  665,  723,    0,  659,  647,  652,  655,  651,    0,
      723,  635,  620,    0,  622,  631,  131,  634,  620,  613,
      626,    0,  623,  139,  614,  628,  147,  651,  650,  630,
      635,  638,  116,  611,  617,  609,  605,  137,  598,  613,
      612,  611,  601,  596,  593,  597,  591,    0,  154,  158,
      598,  608,  585,  595,  588,  153,  156,  604,  113,  599,
      585,  584,  153,  592,  157,  587,  140,  583,  589,  588,
      576,  723,  723,  723,  616,    0,  207,  208,  723,  597,
      199,  596,  595,  210,  594,  593,  184,  592,  723,  612,

      625,  723,  610,  723,    0,  592,  599,  588,  593,  580,
      568,  578,  573,  574,  557,  555,  181,  573,  558,  566,
      566,  550,  557,  565,  547,  561,  723,  723,  572,  579,
      568,  543,  545,  545,  539,  553,  556,  551,  544,  534,
      552,  547,  539,  547,  540,  182,  546,  532,  534,  524,
        0,  526,  528,  521,  539,  520,  527,  534,    0,  525,
      531,  175,  532,  529,  512,  518,  517,  525,  524,  519,
      507,  506,  192,  505,  505,  508,  517,  516,    0,  515,
      499,  506,  509,  723,  540,    0,    0,    0,    0,  490,
        0,  503,    0,  505,  493,  502,  496,    0,  495,  487,

        0,    0,  498,  481,    0,    0,  506,  490,  498,  497,
      482,    0,    0,  480,  485,    0,    0,  494,  486,  484,
      475,  474,  481,  478,   45,  490,    0,  469,  469,  470,
      472,  180,  476,  467,    0,    0,  470,  463,  481,  476,
      456,  461,  474,  476,  197,  460,  461,    0,  465,  197,
      459,  469,    0,  448,    0,    0,  204,    0,  465,    0,
      470,    0,    0,    0,  454,  461,  460,  453,  458,    0,
      447,  458,    0,  447,  455,    0,    0,    0,    0,  450,
      453,  456,  434,  451,  445,  441,  448,  439,  449,  437,
      436,    0,  442,  437,  425,  424,  424,  426,  427,  428,

      427,  432,  431,    0,  416,  432,  410,  424,  419,  416,
      429,  414,  423,  422,  410,  418,  416,    0,  417,  416,
        0,  217,  400,  405,  404,  398,  399,  397,  411,    0,
      399,    0,  394,    0,    0,  408,    0,  406,  401,  384,
        0,    0,  405,  393,    0,  401,  386,    0,    0,  399,
        0,  397,    0,  386,  387,  384,  376,  378,  378,  380,
      394,  378,    0,    0,    0,  385,  387,  367,  381,  186,
      388,  190,  383,  209,  373,  381,    0,    0,  370,    0,
        0,  370,  364,    0,    0,  368,    0,  361,  373,    0,
        0,  361,    0,  366,  373,  364,  370,  371,    0,  361,

      354,  366,  349,  357,  352,  349,  350,  346,  345,  347,
      343,  357,  359,  350,  339,    0,  354,    0,    0,  351,
        0,    0,    0,  340,  339,  335,  344,  350,  347,  331,
      334,  342,  334,  326,  332,  338,  322,    0,  333,  319,
      321,  332,  329,  331,    0,  331,  330,    0,    0,  330,
      324,    0,  320,  310,  314,  308,  312,  308,    0,    0,
      322,  321,  303,  313,  291,  300,  292,  284,    0,    0,
      280,  278,    0,  233,  214,  227,  223,    0,  224,  209,
        0,    0,  228,    0,  220,  219,    0,    0,    0,  188,
        0,  185,    0,  173,  109,    0,  723,  279,  286,  293,

      300,  307,  314,  126,  321,  328,  335,  342,  349,  355
    } ;

static yyconst flex_int16_t yy_def[611] =
    {   0,
      597,    1,  598,  598,  599,  599,  600,  600,  601,  601,
      602,  602,  602,  602,  602,  602,  602,  602,  597,  597,
      597,  597,  597,  597,  597,  603,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  604,  604,  604,  604,  604,  604,  597,  597,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  597,  597,  597,  605,
      597,  606,  607,  597,  607,  608,  597,  608,  609,  597,
      609,  597,  597,  597,  597,  597,  597,  603,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,

      597,  610,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  604,  604,  604,  604,  604,  604,  604,
      597,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  597,  597,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  597,  597,  597,  597,  605,  606,  606,  597,  607,
      607,  607,  608,  608,  608,  609,  609,  609,  597,  597,

      610,  597,  597,  597,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  597,  597,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  597,  597,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,

      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,

      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,

      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,    0,  597,  597,  597,

      597,  597,  597,  597,  597,  597,  597,  597,  597,  597
    } ;

static yyconst flex_int16_t yy_nxt[795] =
    {   0,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   43,   43,   43,   44,   43,   43,
       45,   46,   47,   43,   43,   43,   43,   20,   48,   43,
       49,   50,   51,   52,   53,   54,   55,   56,   43,   57,
       43,   58,   59,   43,   60,   61,   62,   43,   63,   64,
       65,   43,   43,   66,   43,   43,   43,   67,   68,   27,
       69,   71,   71,   74,   74,   77,   77,   80,   80,   93,
       72,   72,   97,   94,  104,   94,  105,   95,   96,   98,
       99,  101,  106,  110,  384,  102,  107,  116,  111,  117,

      103,  385,   78,   78,  122,   75,   75,  118,  123,  124,
      127,  163,   81,   81,  108,   82,   82,  125,  130,  133,
      126,  128,  131,  155,  129,  165,  158,  164,  134,  135,
      156,  114,  132,  157,  159,  175,  176,  183,  136,  160,
      137,  138,  166,  139,  192,  177,  140,  179,  141,  168,
      169,  596,  178,  170,  180,  181,  142,  171,  172,  195,
      267,  173,  188,  143,  174,  144,  189,  197,  232,  145,
      198,  146,  233,  200,  147,   94,  191,  148,  149,  268,
      150,  151,  152,  153,  184,  154,  194,  104,  220,  105,
      213,  214,  224,  238,  272,  239,  225,  249,  221,  252,

      253,  278,  262,  264,  192,  279,  275,  226,  263,  297,
      250,  273,  254,  255,  251,  276,  265,  256,  597,  188,
      195,  197,  597,  189,  198,  323,  298,  324,  402,  338,
      299,  350,  391,  392,  595,  419,  191,  339,  325,  507,
      508,  351,  407,  408,  594,  510,  409,  194,  593,  410,
      411,  511,  403,  412,  513,  413,  414,  514,  415,  420,
      466,  467,  468,  469,  582,  581,  470,  592,  591,  471,
      590,  589,  588,  472,  587,  473,  474,  586,  475,   70,
       70,   70,   70,   70,   70,   70,   73,   73,   73,   73,
       73,   73,   73,   76,   76,   76,   76,   76,   76,   76,

       79,   79,   79,   79,   79,   79,   79,   80,   80,   80,
       80,   80,   80,   80,   88,   88,   88,   88,   88,   88,
       88,  186,  585,  186,  186,  584,  186,  186,  187,  583,
      187,  187,  187,  187,  187,  190,  190,  582,  190,  190,
      190,  190,  193,  193,  193,  581,  193,  193,  193,  196,
      580,  196,  196,  196,  196,  201,  201,  201,  201,  201,
      201,  201,  579,  578,  577,  576,  575,  574,  573,  572,
      571,  570,  569,  568,  567,  566,  565,  564,  563,  562,
      561,  560,  559,  558,  557,  556,  555,  554,  553,  552,
      551,  550,  549,  548,  547,  546,  545,  544,  543,  542,

      541,  540,  539,  538,  537,  536,  535,  534,  533,  532,
      531,  530,  529,  528,  527,  526,  525,  499,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  512,  509,
      506,  505,  504,  503,  502,  501,  500,  499,  498,  497,
      496,  495,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      477,  476,  465,  465,  464,  463,  462,  461,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  451,  335,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,

      430,  429,  428,  427,  302,  426,  425,  424,  423,  422,
      421,  418,  417,  416,  406,  405,  404,  401,  400,  399,
      398,  397,  396,  301,  395,  394,  393,  390,  389,  388,
      387,  386,  383,  382,  381,  380,  379,  378,  377,  313,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  285,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  337,  289,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,

      311,  310,  309,  288,  287,  286,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  203,  202,  285,  197,
      197,  194,  194,  191,  191,  284,  283,  282,  281,  280,
      277,  274,  271,  270,  269,  266,  261,  260,  259,  258,
      257,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      237,  236,  235,  234,  231,  230,  229,  228,  227,  223,
      222,  219,  218,  217,  216,  215,  212,  211,  210,  205,
      209,  208,  207,  206,  205,  204,  109,  203,  202,   89,
      199,   86,  197,  194,  191,  185,  182,  167,  120,  162,

      161,  121,  120,  119,  115,  113,  112,  109,  100,   92,
       91,   90,   89,   87,   86,  597,   85,   85,   84,   84,
       83,   83,   19,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597

    } ;

static yyconst flex_int16_t yy_chk[795] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    7,    8,    9,   10,   32,
        3,    4,   33,   32,   36,   33,   36,   32,   32,   33,
       33,   35,   37,   39,  325,   35,   37,   44,   39,   44,

       35,  325,    7,    8,   50,    5,    6,   44,   50,   50,
       52,   60,    9,   10,   37,    9,   10,   51,   53,   54,
       51,   52,   53,   56,   52,   62,   57,   60,   54,   54,
       56,  604,   53,   56,   57,   65,   65,   68,   54,   57,
       54,   55,   62,   55,   75,   65,   55,   66,   55,   64,
       64,  595,   65,   64,   66,   66,   55,   64,   64,   78,
      169,   64,   72,   55,   64,   55,   72,   81,  143,   55,
       81,   55,  143,   94,   55,   94,   75,   55,   55,  169,
       55,   55,   55,   55,   68,   55,   78,  105,  134,  105,
      127,  127,  137,  148,  173,  148,  137,  159,  134,  160,

      160,  177,  166,  167,  191,  177,  175,  137,  166,  217,
      159,  173,  160,  160,  159,  175,  167,  160,  187,  188,
      194,  197,  187,  188,  197,  246,  217,  246,  345,  262,
      217,  273,  332,  332,  594,  357,  191,  262,  246,  470,
      470,  273,  350,  350,  592,  472,  350,  194,  590,  350,
      350,  472,  345,  350,  474,  350,  350,  474,  350,  357,
      422,  422,  422,  422,  586,  585,  422,  583,  580,  422,
      579,  577,  576,  422,  575,  422,  422,  574,  422,  598,
      598,  598,  598,  598,  598,  598,  599,  599,  599,  599,
      599,  599,  599,  600,  600,  600,  600,  600,  600,  600,

      601,  601,  601,  601,  601,  601,  601,  602,  602,  602,
      602,  602,  602,  602,  603,  603,  603,  603,  603,  603,
      603,  605,  572,  605,  605,  571,  605,  605,  606,  568,
      606,  606,  606,  606,  606,  607,  607,  567,  607,  607,
      607,  607,  608,  608,  608,  566,  608,  608,  608,  609,
      565,  609,  609,  609,  609,  610,  610,  610,  610,  610,
      610,  610,  564,  563,  562,  561,  558,  557,  556,  555,
      554,  553,  551,  550,  547,  546,  544,  543,  542,  541,
      540,  539,  537,  536,  535,  534,  533,  532,  531,  530,
      529,  528,  527,  526,  525,  524,  520,  517,  515,  514,

      513,  512,  511,  510,  509,  508,  507,  506,  505,  504,
      503,  502,  501,  500,  498,  497,  496,  495,  494,  492,
      489,  488,  486,  483,  482,  479,  476,  475,  473,  471,
      469,  468,  467,  466,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  452,  450,  447,  446,  444,  443,  440,
      439,  438,  436,  433,  431,  429,  428,  427,  426,  425,
      424,  423,  420,  419,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  405,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,

      375,  374,  372,  371,  369,  368,  367,  366,  365,  361,
      359,  354,  352,  351,  349,  347,  346,  344,  343,  342,
      341,  340,  339,  338,  337,  334,  333,  331,  330,  329,
      328,  326,  324,  323,  322,  321,  320,  319,  318,  315,
      314,  311,  310,  309,  308,  307,  304,  303,  300,  299,
      297,  296,  295,  294,  292,  290,  285,  283,  282,  281,
      280,  278,  277,  276,  275,  274,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  261,  260,  258,  257,
      256,  255,  254,  253,  252,  250,  249,  248,  247,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,

      234,  233,  232,  231,  230,  229,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  203,  201,  200,  198,
      196,  195,  193,  192,  190,  185,  181,  180,  179,  178,
      176,  174,  172,  171,  170,  168,  165,  164,  163,  162,
      161,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      147,  146,  145,  144,  142,  141,  140,  139,  138,  136,
      135,  133,  131,  130,  129,  128,  126,  125,  123,  122,
      119,  118,  117,  116,  115,  112,  109,  104,  102,   88,
       87,   86,   79,   76,   73,   69,   67,   63,   61,   59,

       58,   48,   46,   45,   42,   41,   40,   38,   34,   31,
       29,   28,   26,   24,   21,   19,   18,   17,   16,   15,
       12,   11,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597,  597,  597,  597,  597,  597,  597,
      597,  597,  597,  597

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[153] =
    {   0,
0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lshScanner.l"
#line 2 "lshScanner.l"
//lshScanner.l
//----------------------------------------------------------------------
/*
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.
 *      
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *      
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */

//----------------------------------------------------------------------
#include <iostream>
#include <string>
using namespace std;

#include "run/stmts/stmtNode.h"
#include "lshParser.h"

#undef YY_INPUT








#line 906 "lshScanner.c"

#define INITIAL 0
#define cm 1
#define strd 2
#define strs 3
#define rexp 4
#define endrexp 5
#define endcm 6
#define endstrd 7
#define endstrs 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 42 "lshScanner.l"


   /*=================================================================*/
   /* Comentarios */

#line 1134 "lshScanner.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 598 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 723 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "lshScanner.l"
BEGIN(cm);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "lshScanner.l"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "lshScanner.l"

	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 50 "lshScanner.l"
stmtNode::newLine ();
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "lshScanner.l"
BEGIN(INITIAL);
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 53 "lshScanner.l"
stmtNode::newLine ();
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 55 "lshScanner.l"
stmtNode::newLine ();
	YY_BREAK
/*=================================================================*/							
/* Espaciado */
case 8:
YY_RULE_SETUP
#line 60 "lshScanner.l"

	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 62 "lshScanner.l"
stmtNode::newLine ();
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cm):
case YY_STATE_EOF(strd):
case YY_STATE_EOF(strs):
case YY_STATE_EOF(rexp):
case YY_STATE_EOF(endrexp):
case YY_STATE_EOF(endcm):
case YY_STATE_EOF(endstrd):
case YY_STATE_EOF(endstrs):
#line 64 "lshScanner.l"
{  stmtNode::newLine (); yyterminate(); }
	YY_BREAK
/*=================================================================*/
/* Null */
case 10:
YY_RULE_SETUP
#line 69 "lshScanner.l"
return NULLTOKEN;
	YY_BREAK
/*=================================================================*/
/* Booleanos */
case 11:
YY_RULE_SETUP
#line 74 "lshScanner.l"
return TRUE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "lshScanner.l"
return FALSE;
	YY_BREAK
/*=================================================================*/
/* Numéricos */
case 13:
YY_RULE_SETUP
#line 81 "lshScanner.l"
{
   yylval.fval = new num (atof (yytext));
   return NUM;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "lshScanner.l"
{
   yylval.fval = new num (atof (yytext));
   return SNUM;
}
	YY_BREAK
/*=================================================================*/
/* Cadenas de texto */
case 15:
YY_RULE_SETUP
#line 93 "lshScanner.l"
BEGIN(strd);
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 94 "lshScanner.l"
{
   yylval.str = new string (yytext);
   BEGIN(endstrd);
   return STR;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 99 "lshScanner.l"
{
   yylval.str = new string ("");
   BEGIN(INITIAL);
   return STR;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "lshScanner.l"
{
   BEGIN(INITIAL);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "lshScanner.l"
BEGIN(strs);
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 109 "lshScanner.l"
{
   yylval.str = new string (yytext);
   BEGIN(endstrs);
   return STR;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 114 "lshScanner.l"
{
   yylval.str = new string ("");
   BEGIN(INITIAL);
   return STR;
}					
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 119 "lshScanner.l"
BEGIN(INITIAL);
	YY_BREAK
/*=================================================================*/
/* Expresiones regulares */							
case 23:
YY_RULE_SETUP
#line 124 "lshScanner.l"
BEGIN(rexp);		
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "lshScanner.l"
{
   yylval.str = new string (yytext);
   BEGIN(endrexp);
   return REXP;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 130 "lshScanner.l"
{	
   yylval.str = new string ("");
   BEGIN(INITIAL);
   return REXP;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 135 "lshScanner.l"
BEGIN(INITIAL);
	YY_BREAK
/*=================================================================*/
/* Variables */
case 27:
YY_RULE_SETUP
#line 140 "lshScanner.l"
return GLOBAL;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 142 "lshScanner.l"
return GETENV;
	YY_BREAK
/*=================================================================*/
/* Funciones */
case 29:
YY_RULE_SETUP
#line 147 "lshScanner.l"
return FUNCTION;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 149 "lshScanner.l"
return DECORATOR;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 151 "lshScanner.l"
return PARTIALFUNC;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 153 "lshScanner.l"
return CONTEXTFUNC;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 155 "lshScanner.l"
return RET;
	YY_BREAK
/*=================================================================*/
/* Clases */
case 34:
YY_RULE_SETUP
#line 160 "lshScanner.l"
return CLASS;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 162 "lshScanner.l"
return NEW;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 164 "lshScanner.l"
return PRIVATE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 166 "lshScanner.l"
return CLASSACCESS;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 168 "lshScanner.l"
return EXTENDS;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "lshScanner.l"
return THIS;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 172 "lshScanner.l"
return PARENT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 174 "lshScanner.l"
return STATIC;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 176 "lshScanner.l"
return NAMESPACE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 178 "lshScanner.l"
return GETCLASS;
	YY_BREAK
/*=================================================================*/
/* Sentencias de control */
case 44:
YY_RULE_SETUP
#line 183 "lshScanner.l"
return INCLUDE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 185 "lshScanner.l"
return IF;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 187 "lshScanner.l"
return ELSE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 189 "lshScanner.l"
return ELSEIF;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 191 "lshScanner.l"
return WITH;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 193 "lshScanner.l"
return DO;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 195 "lshScanner.l"
return WHILE;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 197 "lshScanner.l"
return FOR;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 199 "lshScanner.l"
return AS;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 201 "lshScanner.l"
return IN;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 203 "lshScanner.l"
return SWITCH;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 205 "lshScanner.l"
return CASE; 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 207 "lshScanner.l"
return DEFAULT; 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 209 "lshScanner.l"
return BREAK;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 211 "lshScanner.l"
return CONTINUE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 213 "lshScanner.l"
return EXIT;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 215 "lshScanner.l"
return GOTO;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 217 "lshScanner.l"
return OPINC;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 219 "lshScanner.l"
return THROW;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 221 "lshScanner.l"
return CATCH;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 223 "lshScanner.l"
return TRY;
	YY_BREAK
/*=================================================================*/
/* Entrada/salida */
case 65:
YY_RULE_SETUP
#line 228 "lshScanner.l"
return PRINT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 230 "lshScanner.l"
return INPUT;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 232 "lshScanner.l"
return INPUTLINE;
	YY_BREAK
/*=================================================================*/
/* Operadores */
case 68:
YY_RULE_SETUP
#line 237 "lshScanner.l"
return FLOW;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 239 "lshScanner.l"
return FLOWLINE;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 241 "lshScanner.l"
return TYPEOF;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 243 "lshScanner.l"
return SIZEOF;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 245 "lshScanner.l"
return DATINFO;
	YY_BREAK
/*=================================================================*/
/* Operadores lógicos */
case 73:
YY_RULE_SETUP
#line 250 "lshScanner.l"
return EMPTY;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 252 "lshScanner.l"
return ISNULL;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 254 "lshScanner.l"
return ISBOOL;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 256 "lshScanner.l"
return ISNUM;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 258 "lshScanner.l"
return ISSTRING;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 260 "lshScanner.l"
return ISARRAY;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 262 "lshScanner.l"
return ISOBJECT;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 264 "lshScanner.l"
return EQL;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 266 "lshScanner.l"
return IDEN;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 268 "lshScanner.l"
return NIDEN;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 270 "lshScanner.l"
return AND_OP;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 272 "lshScanner.l"
return OR_OP;
	YY_BREAK
/*=================================================================*/
/* Operadores aritméticos */
case 85:
YY_RULE_SETUP
#line 277 "lshScanner.l"
return SIZE;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 279 "lshScanner.l"
return SQRT;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 281 "lshScanner.l"
return INC;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 283 "lshScanner.l"
return DEC;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 285 "lshScanner.l"
return ADDASIG;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 287 "lshScanner.l"
return SUBASIG;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 289 "lshScanner.l"
return PRODASIG;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 291 "lshScanner.l"
return DIVASIG;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 293 "lshScanner.l"
return POWASIG;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 295 "lshScanner.l"
return MODASIG;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 297 "lshScanner.l"
return CATASIG;
	YY_BREAK
/*=================================================================*/
/* Operadores cadenas */
case 96:
YY_RULE_SETUP
#line 302 "lshScanner.l"
return EXPLODE; 
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 304 "lshScanner.l"
return IMPLODE;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 306 "lshScanner.l"
return FIND;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 308 "lshScanner.l"
return REPLACE;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 310 "lshScanner.l"
return SUBREPLACE;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 312 "lshScanner.l"
return UPPER;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 314 "lshScanner.l"
return LOWER;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 316 "lshScanner.l"
return SPRINTF;
	YY_BREAK
/*=================================================================*/
/* Operadores expresiones regulares */
case 104:
YY_RULE_SETUP
#line 320 "lshScanner.l"
return SEARCH;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 322 "lshScanner.l"
return REGEXP;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 324 "lshScanner.l"
return MATCH;
	YY_BREAK
/*=================================================================*/
/* Operadores array */
case 107:
YY_RULE_SETUP
#line 329 "lshScanner.l"
return REDUCE;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 331 "lshScanner.l"
{  return ARRAYCHUNK;  }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 333 "lshScanner.l"
return SEARCH;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 335 "lshScanner.l"
return ARRAYLAST;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 337 "lshScanner.l"
return ARRAYFIRST;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 339 "lshScanner.l"
return ARRAYINSERT;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 341 "lshScanner.l"
return ARRAYDELETE;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 343 "lshScanner.l"
return ARRAYUNSHIFT;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 345 "lshScanner.l"
return ARRAYSHIFT;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 347 "lshScanner.l"
return ARRAYPOP;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 349 "lshScanner.l"
return ARRAYPUSH;
	YY_BREAK
/*=================================================================*/
/* Conversión de tipos */
case 118:
YY_RULE_SETUP
#line 353 "lshScanner.l"
return CINT;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 355 "lshScanner.l"
return CFLOAT;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 357 "lshScanner.l"
return CBOOL;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 359 "lshScanner.l"
return CSTR;
	YY_BREAK
/*=================================================================*/
/* Fechas */
case 122:
YY_RULE_SETUP
#line 364 "lshScanner.l"
return DATE;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 366 "lshScanner.l"
return TIME;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 368 "lshScanner.l"
return SLEEP;
	YY_BREAK
/*=================================================================*/
/* Ficheros */
case 125:
YY_RULE_SETUP
#line 373 "lshScanner.l"
return FTOKEN;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 375 "lshScanner.l"
return FPUT;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 377 "lshScanner.l"
return FGET;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 379 "lshScanner.l"
return FREAD;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 381 "lshScanner.l"
return FWRITE;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 383 "lshScanner.l"
return FAPP;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 385 "lshScanner.l"
return FCLOSE;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 387 "lshScanner.l"
return FTELL;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 389 "lshScanner.l"
return FSEEK;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 391 "lshScanner.l"
return FSET;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 393 "lshScanner.l"
return FCUR;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 395 "lshScanner.l"
return FEND;
	YY_BREAK
/*=================================================================*/
/* Procesos */
case 137:
YY_RULE_SETUP
#line 400 "lshScanner.l"
return EXEC;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 402 "lshScanner.l"
return EVAL;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 404 "lshScanner.l"
return FORK;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 406 "lshScanner.l"
return WAIT;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 408 "lshScanner.l"
return GETPID;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 410 "lshScanner.l"
return GETPPID;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 412 "lshScanner.l"
return PROCESSTOKEN;
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 414 "lshScanner.l"
return SIGNAL;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 416 "lshScanner.l"
return SHANDLER;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 418 "lshScanner.l"
return EXITPROCESS;
	YY_BREAK
/*=================================================================*/
/* Extensiones */
case 147:
YY_RULE_SETUP
#line 423 "lshScanner.l"
return LOAD_MODULE;
	YY_BREAK
/*=================================================================*/
/* Identificadores */
case 148:
YY_RULE_SETUP
#line 428 "lshScanner.l"
{
   yylval.str = new string (yytext);
   return ID;
}		
	YY_BREAK
/*=================================================================*/
/* Otros */		
case 149:
YY_RULE_SETUP
#line 436 "lshScanner.l"
return ';';
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 438 "lshScanner.l"
return *yytext;	
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 440 "lshScanner.l"
cout << "Error: lexical error, unexpected character (" << yytext << ")\n";
	YY_BREAK
/*=================================================================*/
/* Fco. Javier Bohórquez Ogalla */
case 152:
YY_RULE_SETUP
#line 444 "lshScanner.l"
ECHO;
	YY_BREAK
#line 2064 "lshScanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 598 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 598 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 597);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 443 "lshScanner.l"
